export const LOGIN_UPDATE = 'login_update'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGOUT_USER = 'logout_user'
export const MOVIES_FETCH_SUCCESS = 'movies_fetch_success'
export const MOVIES_FETCH_FAIL = 'movies_fetch_fail'
